/**
 * Full catalog metadata for Shen Sha v2.0 (default catalog only).
 */

import type { ShenShaCatalogEntry } from "./types";
import { SHEN_SHA_CATALOG_VERSION } from "./types";

export const SHEN_SHA_CATALOG_V2: ShenShaCatalogEntry[] = [
  // —— Legacy 13 (formulas unchanged) ——
  {
    key: "noble",
    chineseName: "天乙贵人",
    vietnameseName: "Thiên Ất Quý Nhân",
    aliases: ["tianyi", "Thiên Ất"],
    category: "quý_nhân",
    lookupBasis: "dayStem→branches",
    ruleVariant: "legacy.tianyi",
    sourceId: "shensha.tianyi.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "wenchang",
    chineseName: "文昌",
    vietnameseName: "Văn Xương",
    aliases: [],
    category: "văn_tinh",
    lookupBasis: "dayStem→branch",
    ruleVariant: "legacy.wenchang",
    sourceId: "shensha.wenchang.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "blood",
    chineseName: "血刃",
    vietnameseName: "Huyết Nhận",
    aliases: ["Huyết Nhẫn"],
    category: "sát_tinh",
    lookupBasis: "dayStem→branch",
    ruleVariant: "legacy.xueren",
    sourceId: "shensha.xueren.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "tao_hua_xian_chi",
    chineseName: "桃花/咸池",
    vietnameseName: "Đào Hoa",
    aliases: ["Đào Hoa", "Hàm Trì", "桃花", "咸池"],
    category: "tình_duyên",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.taohua_xianchi",
    sourceId: "shensha.taohua_xianchi.yearOrDay.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
    notes: "Một entity duy nhất — không tách Đào Hoa / Hàm Trì.",
  },
  {
    key: "horse",
    chineseName: "驿马",
    vietnameseName: "Dịch Mã",
    aliases: [],
    category: "động",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.yima",
    sourceId: "shensha.yima.yearOrDay.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "canopy",
    chineseName: "华盖",
    vietnameseName: "Hoa Cái",
    aliases: [],
    category: "cô_cao",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.huagai",
    sourceId: "shensha.huagai.v1",
    weightClass: "auxiliary",
    traditionalTone: "trung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "jie",
    chineseName: "劫煞",
    vietnameseName: "Kiếp Sát",
    aliases: [],
    category: "sát_tinh",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.jiesha",
    sourceId: "shensha.jiesha.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "void",
    chineseName: "亡神",
    vietnameseName: "Vong Thần",
    aliases: [],
    category: "sát_tinh",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.wangshen",
    sourceId: "shensha.wangshen.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
    notes: "Không trùng Không Vong (xunKong).",
  },
  {
    key: "tai",
    chineseName: "灾煞",
    vietnameseName: "Tai Sát",
    aliases: [],
    category: "sát_tinh",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.taisha",
    sourceId: "shensha.taisha.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
    notes: "Không thêm Bạch Hổ riêng (trùng tượng / dị bản).",
  },
  {
    key: "general",
    chineseName: "将星",
    vietnameseName: "Tướng Tinh",
    aliases: [],
    category: "quý_tinh",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.jiangxing",
    sourceId: "shensha.jiangxing.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "lonely",
    chineseName: "孤辰",
    vietnameseName: "Cô Thần",
    aliases: [],
    category: "cô_quả",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.guchen",
    sourceId: "shensha.guchen.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "widow",
    chineseName: "寡宿",
    vietnameseName: "Quả Tú",
    aliases: [],
    category: "cô_quả",
    lookupBasis: "yearOrDayBranch→branch",
    ruleVariant: "legacy.guasu",
    sourceId: "shensha.guasu.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  {
    key: "tian_gou",
    chineseName: "天勾",
    vietnameseName: "Thiên Câu",
    aliases: ["Thiên Cẩu", "Thiên Cầu", "天勾"],
    category: "sát_tinh",
    lookupBasis: "monthBranch+3",
    ruleVariant: "legacy.tiangou.monthPlus3",
    sourceId: "shensha.tiangou.monthPlus3.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "LEGACY",
    inDefaultCatalog: true,
  },
  // —— New 7 ——
  {
    key: "tian_de",
    chineseName: "天德",
    vietnameseName: "Thiên Đức",
    aliases: ["天德贵人"],
    category: "đức_tinh",
    lookupBasis: "monthBranch→stemOrBranch",
    ruleVariant: "sanming.tiande.month",
    sourceId: "sanming.tiande.month.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "A",
    inDefaultCatalog: true,
  },
  {
    key: "yue_de",
    chineseName: "月德",
    vietnameseName: "Nguyệt Đức",
    aliases: ["月德贵人"],
    category: "đức_tinh",
    lookupBasis: "monthBranch→stem",
    ruleVariant: "sanming.yuede.month",
    sourceId: "sanming.yuede.month.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "A",
    inDefaultCatalog: true,
  },
  {
    key: "xue_tang",
    chineseName: "学堂",
    vietnameseName: "Học Đường",
    aliases: ["學堂"],
    category: "văn_tinh",
    lookupBasis: "dayStem→changShengBranch",
    ruleVariant: "sanming.dayStemChangSheng",
    sourceId: "sanming.xuetang.dayStemChangSheng.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "A_MINUS",
    inDefaultCatalog: true,
    notes: "Không trộn dị bản Nạp Âm.",
  },
  {
    key: "ci_guan",
    chineseName: "词馆",
    vietnameseName: "Từ Quán",
    aliases: ["詞館"],
    category: "văn_tinh",
    lookupBasis: "dayStem→linGuanBranch",
    ruleVariant: "sanming.dayStemLinGuan",
    sourceId: "sanming.ciguan.dayStemLinGuan.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "A_MINUS",
    inDefaultCatalog: true,
  },
  {
    key: "jin_yu",
    chineseName: "金舆",
    vietnameseName: "Kim Dư",
    aliases: ["金輿"],
    category: "xe_cư",
    lookupBasis: "dayStemLu+2",
    ruleVariant: "sanming.jinyu.luPlus2",
    sourceId: "sanming.jinyu.luPlus2.v1",
    weightClass: "auxiliary",
    traditionalTone: "cát",
    priorityClass: "B",
    inDefaultCatalog: true,
    notes: "Không đưa Lộc vào shenSha[].",
  },
  {
    key: "yuan_chen",
    chineseName: "元辰",
    vietnameseName: "Nguyên Thần",
    aliases: [],
    category: "sát_tinh",
    lookupBasis: "yearStemPolarity+gender+yearBranch",
    ruleVariant: "sanming.yuanchen.genderYear",
    sourceId: "sanming.yuanchen.genderYear.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "B",
    inDefaultCatalog: true,
  },
  {
    key: "tian_luo_di_wang",
    chineseName: "天罗地网",
    vietnameseName: "Thiên La / Địa Võng",
    aliases: ["tian_luo", "di_wang", "天罗", "地网"],
    category: "la_võng",
    lookupBasis: "natalPair戌亥|辰巳",
    ruleVariant: "sanming.tianluodiwang.pair",
    sourceId: "sanming.tianluodiwang.pair.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "B_MINUS",
    inDefaultCatalog: true,
    notes: "Một nhóm — runtime emit key tian_luo và/hoặc di_wang khi đủ cặp.",
  },
];

/** Special-day markers (not in shenSha[]). */
export const SPECIAL_DAY_CATALOG_V2: ShenShaCatalogEntry[] = [
  {
    key: "kuiGang",
    chineseName: "魁罡",
    vietnameseName: "Khôi Cương",
    aliases: [],
    category: "nhật_trụ_đặc_thù",
    lookupBasis: "dayPillar",
    ruleVariant: "sanming.kuigang.dayPillar",
    sourceId: "sanming.kuigang.dayPillar.v1",
    weightClass: "auxiliary",
    traditionalTone: "trung",
    priorityClass: "B",
    inDefaultCatalog: true,
    notes: "Marker cấu trúc — không gắn hung/cát tự động.",
  },
  {
    key: "yinYangMisalignment",
    chineseName: "阴差阳错",
    vietnameseName: "Âm Dương Sai Thác",
    aliases: [],
    category: "nhật_trụ_đặc_thù",
    lookupBasis: "dayPillar",
    ruleVariant: "sanming.yinyangMisalignment.dayPillar",
    sourceId: "sanming.yinyangMisalignment.dayPillar.v1",
    weightClass: "auxiliary",
    traditionalTone: "trung",
    priorityClass: "B",
    inDefaultCatalog: true,
    notes: "Không tự kết luận hôn nhân / ly hôn.",
  },
  {
    key: "fourWaste",
    chineseName: "四废",
    vietnameseName: "Tứ Phế",
    aliases: [],
    category: "nhật_trụ_đặc_thù",
    lookupBasis: "seasonMonth+dayPillar",
    ruleVariant: "sanming.fourWaste.seasonDay",
    sourceId: "sanming.fourWaste.seasonDay.v1",
    weightClass: "auxiliary",
    traditionalTone: "hung",
    priorityClass: "B",
    inDefaultCatalog: true,
  },
  {
    key: "tenEvilGreatDefeat",
    chineseName: "十恶大败",
    vietnameseName: "Thập Ác Đại Bại",
    aliases: [],
    category: "nhật_trụ_đặc_thù",
    lookupBasis: "dayPillar+optionalYearPair",
    ruleVariant: "sanming.tenEvilGreatDefeat",
    sourceId: "sanming.tenEvilGreatDefeat.v1",
    weightClass: "auxiliary",
    traditionalTone: "trung",
    priorityClass: "B",
    inDefaultCatalog: true,
    notes: "Không display ĐẠI HUNG. Phân biệt baseListHit / refinedYearRuleHit.",
  },
];

export function buildShenShaCatalogJson() {
  return {
    shenShaCatalogVersion: SHEN_SHA_CATALOG_VERSION,
    engineCalculatorUnchanged: "0.3.2-core",
    principle:
      "All markers are auxiliary. Never drive usefulGod, patterns, body strength, or automatic good/bad conclusions.",
    defaultGroups: SHEN_SHA_CATALOG_V2.length,
    specialDayMarkers: SPECIAL_DAY_CATALOG_V2.length,
    totalGroups: SHEN_SHA_CATALOG_V2.length + SPECIAL_DAY_CATALOG_V2.length,
    catalog: SHEN_SHA_CATALOG_V2,
    specialDayCatalog: SPECIAL_DAY_CATALOG_V2,
    researchExtendedExcluded: [
      "Hồng Diễm",
      "Bạch Hổ (riêng)",
      "Thiên Y",
      "Quốc Ấn",
      "Phúc Tinh Quý Nhân",
      "Thái Cực Quý Nhân",
      "Thiên Trù",
      "Lục Ách",
      "Câu Giảo",
      "Tang Môn",
      "Điếu Khách",
    ],
  };
}
